# Generated by Django 5.2.7 on 2025-11-11 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='codigo_guia',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='envio',
            name='cliente',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion_destino',
            field=models.CharField(default='Sin especificar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion_origen',
            field=models.CharField(default='Sin especificar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
