# Generated by Django 5.2.8 on 2025-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_envio_codigo_guia_remove_envio_creado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="envio",
            name="fecha_envio",
        ),
        migrations.AlterField(
            model_name="envio",
            name="cliente",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="envio",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="envio",
            name="direccion_destino",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="envio",
            name="direccion_origen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="envio",
            name="estado",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="envio",
            name="numero_guia",
            field=models.CharField(max_length=255),
        ),
    ]
